<a href="https://colab.research.google.com/github/KsiuTretyakova/python_for_ML_ds_task/blob/main/HW7_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Створення масивів**

Створіть (кожен пункт оцінюється в 0.5 бала):
- Масив зі списку `[5, 15, 25, 35, 45]`
- Масив з нулів розміром 7
- Масив з одиниць розміром 6
- Масив з числами від 10 до 19 використовуючи `np.arange()`

In [1]:
import numpy as np

print("Масив зі списку [5, 15, 25, 35, 45]")
print(f"np.array([5, 15, 25, 35, 45]) => {np.array([5, 15, 25, 35, 45])}")

print("\nМасив з нулів розміром 7")
print(f"np.zeros((7,)) => {np.zeros((7,))}")

print("\nМасив з одиниць розміром 6")
print(f"np.ones((6,)) => {np.ones((6,))}")

print("\nМасив з числами від 10 до 19 використовуючи np.arange()")
print(f"np.arange(10, 20) => {np.arange(10, 20)}")

Масив зі списку [5, 15, 25, 35, 45]
np.array([5, 15, 25, 35, 45]) => [ 5 15 25 35 45]

Масив з нулів розміром 7
np.zeros((7,)) => [0. 0. 0. 0. 0. 0. 0.]

Масив з одиниць розміром 6
np.ones((6,)) => [1. 1. 1. 1. 1. 1.]

Масив з числами від 10 до 19 використовуючи np.arange()
np.arange(10, 20) => [10 11 12 13 14 15 16 17 18 19]



---

**2. Базові операції**

Створіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].

Виконайте наступні операції над **оригінальним** масивом і запишіть у нову змінну результат (кожен пункт оцінюється в 0.5 бала):
- Помножте всі елементи на 2
- Додайте до всіх елементів 10
- Піднесіть всі елементи до квадрату
- Обчисліть квадратний корінь з усіх елементів

Виведіть результат виконання кожної операції.

In [2]:
arr = np.array([12, 24, 36, 48, 60])

arr_m2 = arr * 2
arr_s10 = arr + 10
arr_qrt = arr ** 2
arr_sqrt = np.sqrt(arr)

print(f"Оригінальний масив: {arr}\n")

print(f"Всі елементи помножені на 2: {arr_m2}")
print(f"До всіх елементів додано 10: {arr_s10}")
print(f"Всі елементи піднесені до квадрату: {arr_qrt}")
print(f"Квадратний корінь з усіх елементів: {arr_sqrt}")

Оригінальний масив: [12 24 36 48 60]

Всі елементи помножені на 2: [ 24  48  72  96 120]
До всіх елементів додано 10: [22 34 46 58 70]
Всі елементи піднесені до квадрату: [ 144  576 1296 2304 3600]
Квадратний корінь з усіх елементів: [3.46410162 4.89897949 6.         6.92820323 7.74596669]



---

**3. Статистичні функції**

Створіть Numpy-масив `data` зі значеннями [18, 27, 33, 41, 52, 68, 79].

Обчисліть використовуючи функціонал numpy (кожен пункт оцінюється в 0.5 бала):
- Середнє значення
- Мінімум
- Максимум
- Суму всіх елементів

In [3]:
data = np.array([18, 27, 33, 41, 52, 68, 79])

print(f"Оригінальний масив: {data}\n")

print(f"Середнє значення: {np.mean(data)}")
print(f"Мінімум: {np.min(data)}")
print(f"Максимум: {np.max(data)}")
print(f"Суму всіх елементів: {np.sum(data)}")

Оригінальний масив: [18 27 33 41 52 68 79]

Середнє значення: 45.42857142857143
Мінімум: 18
Максимум: 79
Суму всіх елементів: 318



---

**4. Індексація**

Створіть Numpy-масив `arr` зі значеннями [15, 22, 35, 44, 58, 67].

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перший елемент
- Останній елемент
- Елементи з індексами 1 до 3
- Елементи більші за 40

In [4]:
arr = np.array([15, 22, 35, 44, 58, 67])

print(f"Оригінальний масив: {arr}\n")

print(f"Перший елемент: {arr[0]}")
print(f"Останній елемент: {arr[-1]}")
print(f"Елементи з індексами 1 до 3: {arr[1:4]}")
print(f"Елементи більші за 40: {arr[arr > 40]}")

Оригінальний масив: [15 22 35 44 58 67]

Перший елемент: 15
Останній елемент: 67
Елементи з індексами 1 до 3: [22 35 44]
Елементи більші за 40: [44 58 67]



---


**5. Двовимірні масиви**

Задано матрицю 3x3.

Виконайте наступні дії з функціоналом Numpy (кожен пункт оцінюється в 0.5 бала):
- Виведіть форму (shape) матриці
- Виведіть перший рядок
- Виведіть другу колонку
- Обчисліть суму всіх елементів
- Обчисліть середнє всіх елементів

In [5]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

In [6]:
print(f"Оригінальна матриця: \n{matrix}\n")

print(f"Форма матриці: {matrix.shape}")
print(f"Перший рядок: {matrix[0,:]}")
print(f"Друга колонка: {matrix[:,1]}")
print(f"Сума всіх елементів: {matrix.sum()}")
print(f"Середнє всіх елементів: {matrix.mean()}")

Оригінальна матриця: 
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Форма матриці: (3, 3)
Перший рядок: [2 4 6]
Друга колонка: [ 4 10 16]
Сума всіх елементів: 90
Середнє всіх елементів: 10.0
